# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DANUBEtool
                                 A QGIS plugin
 DANUBE Tool allow you to generate spatialized buildings' material informations from DANUBE database and urban scale typomorphological informations (IGN BDTOPO and/or Geoclimate tool's outputsl) 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-31
        copyright            : (C) 2023 by (C) LRA - ENSAT Toulouse / LMDC - INSA Toulouse / LISST - UT2J
        email                : lra-tech@toulouse.archi.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = '(C) LRA - ENSAT Toulouse / LMDC - INSA Toulouse / LISST - UT2J'
__date__ = '2023-03-31'
__copyright__ = '(C) 2023 by (C) LRA - ENSAT Toulouse / LMDC - INSA Toulouse / LISST - UT2J'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DANUBEtool class from file DANUBEtool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DANUBE_tool import DANUBEtoolPlugin
    return DANUBEtoolPlugin()
